name: Build and deploy to staging
on:
  push:
    branches: staging
  pull_request_review:
    types: [submitted]
    branches: staging
jobs:
  build:
    if: github.event_name == 'push' || github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install dependencies
        run: npm install
      - if: github.event_name == 'push'
        name: Deploy
        env:
          CI: false
          SURGE_LOGIN: "${{ secrets.SURGE_LOGIN }}"
          SURGE_TOKEN: "${{ secrets.SURGE_TOKEN }}"
        run: npm run deploy-staging
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
